/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Crud;
import com.mysql.cj.x.protobuf.MysqlxCrud.Update;
import javax.swing.table.DefaultTableModel;
import student_management_system.Class.Connect;
import student_management_system.Student_information;
import java.time.format.DateTimeFormatter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Time; // For java.sql.Time
import java.text.DateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.SimpleDateFormat;  
import java.time.LocalDate;
import java.time.ZoneId;
/**
 *
 * @author MSI
 */
public final class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Main_navigation
     */
    public Edit() {
        initComponents();
        Student_information.TB(jTable2);
//        setclass();
//        setstarttime();
//        setendtime();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        lastnametxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        birthdatetxt = new com.github.lgooddatepicker.components.DatePicker();
        jLabel8 = new javax.swing.JLabel();
        firstnametxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        contacttxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addresstxt = new javax.swing.JComboBox<>();
        gendertxt = new javax.swing.JComboBox<>();
        classtxt = new javax.swing.JTextField();
        starttxt = new javax.swing.JTextField();
        endtxt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(900, 800));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1100, 911));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(765, 600));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));

        jLabel4.setText("First Name:");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));

        jLabel5.setText("Last Name:");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));

        jLabel6.setText("Gender:");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));

        idtxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        idtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        idtxt.setForeground(new java.awt.Color(153, 153, 255));
        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });

        lastnametxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lastnametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lastnametxt.setForeground(new java.awt.Color(153, 153, 255));
        lastnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnametxtActionPerformed(evt);
            }
        });

        jLabel7.setText("Address:");
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));

        jLabel11.setText("Birth Date:");
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 255));

        birthdatetxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jLabel8.setText("ID:");
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 255));

        firstnametxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        firstnametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        firstnametxt.setForeground(new java.awt.Color(153, 153, 255));
        firstnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnametxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Class:");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));

        jLabel13.setText("Start:");
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 255));

        jLabel14.setText("End:");
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 255));

        emailtxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emailtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emailtxt.setForeground(new java.awt.Color(153, 153, 255));
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });

        contacttxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        contacttxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contacttxt.setForeground(new java.awt.Color(153, 153, 255));
        contacttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacttxtActionPerformed(evt);
            }
        });

        jLabel10.setText("Contact:");
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 255));

        jLabel12.setText("Email:");
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 255));

        addresstxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phnom Penh ", "Banteay Meanchey", "Battambang", "Kampong Cham", "Kampong Chhnang", "Kampong Speu", "Kampong Thom", "Kampot", "Kandal", "Kep", "Koh Kong", "Kratie", "Mondulkiri", "Oddar Meanchey", "Pailin", "Preah Vihear", "Prey Veng", "Pursat", "Ratanakiri", "Siem Reap", "Preah Sihanouk ", "Stung Treng", "Svay Rieng", "Takeo", "Tbong Khmum" }));
        addresstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstxtActionPerformed(evt);
            }
        });

        gendertxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(567, 567, 567))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8)))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(contacttxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(idtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lastnametxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(firstnametxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(birthdatetxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(addresstxt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gendertxt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classtxt)
                    .addComponent(starttxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endtxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gendertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(birthdatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(classtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(starttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(endtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(16, 16, 16))
        );

        jButton4.setText("BACK");
        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("ADD");
        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1446, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void contacttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contacttxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            insert();
            Student_information.TB(jTable2);
        } catch (ParseException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        idtxt.setText("");
        firstnametxt.setText("");
        lastnametxt.setText("");
        gendertxt.setSelectedItem("");
        addresstxt.setSelectedItem("");
        emailtxt.setText("");
        contacttxt.setText("");
        classtxt.setText("");
        starttxt.setText("");
        endtxt.setText("");
        birthdatetxt.setText("");
//        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void lastnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnametxtActionPerformed

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            update();
        } catch (ParseException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Delete();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Student_information stu_nav=new Student_information();
        stu_nav.show();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void firstnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnametxtActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
    DefaultTableModel tblModel = (DefaultTableModel) jTable2.getModel();
        
        String id =tblModel.getValueAt(jTable2.getSelectedRow(),0).toString();
        String firstName= tblModel.getValueAt(jTable2.getSelectedRow(),1).toString();
        String lastName=tblModel.getValueAt(jTable2.getSelectedRow(), 2).toString();
        String gender=tblModel.getValueAt(jTable2.getSelectedRow(),3).toString();
        String birth=tblModel.getValueAt(jTable2.getSelectedRow(),4).toString();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String email=tblModel.getValueAt(jTable2.getSelectedRow(),5).toString();
        String address=tblModel.getValueAt(jTable2.getSelectedRow(),6).toString();
        String classroom=tblModel.getValueAt(jTable2.getSelectedRow(),7).toString();
        
//        String level=tblModel.getValueAt(jTable2.getSelectedRow(),9).toString();
        String start=tblModel.getValueAt(jTable2.getSelectedRow(),10).toString();
        String end=tblModel.getValueAt(jTable2.getSelectedRow(),11).toString();
        String contact=tblModel.getValueAt(jTable2.getSelectedRow(),12).toString();
        
        LocalDate date = LocalDate.parse(birth, formatter);
        idtxt.setText(id);
        firstnametxt.setText(firstName);
        lastnametxt.setText(lastName);
        gendertxt.setSelectedItem(gender);
        birthdatetxt.setDate(date);
        emailtxt.setText(email);
        addresstxt.setSelectedItem(address);
        classtxt.setText(classroom);
        starttxt.setText(start);
        endtxt.setText(end);
        contacttxt.setText(contact);
       
    }//GEN-LAST:event_jTable2MouseClicked

    private void addresstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresstxtActionPerformed
public void insert() throws ParseException {
    String firstname = firstnametxt.getText();
    String lastname = lastnametxt.getText();
    String gender = gendertxt.getSelectedItem().toString();
    String email = emailtxt.getText();
    String address = addresstxt.getSelectedItem().toString();
    
    // Convert birth string to java.sql.Date
    String birthString = birthdatetxt.getDate().toString(); // Assuming this is a text field with date in "MMMM d, yyyy" format
//    Date birthFormatter = new SimpleDateFormat("MMMM d, yyyy").parse(birthString);
    // Convert to SQL Date

    int classroom = Integer.parseInt(classtxt.getText()); 
    DateFormat timeFormatter = new SimpleDateFormat("HH:mm");

    // Convert start and end strings to java.sql.Time
    Time start = new Time(timeFormatter.parse(starttxt.getText()).getTime()); // Assuming you have a field named starttxt
    Time end = new Time(timeFormatter.parse(endtxt.getText()).getTime());
    int contact = Integer.parseInt(contacttxt.getText());

    String insertQuery = """
                        call studentmanagementsystem.InsertStudent(?,?,?,?,?,?,?,?,?,?);
                          """;
    try (Connection con = Connect.getConnection(); 
         PreparedStatement pstmt = con.prepareStatement(insertQuery)) {
        
        // Set parameters for the prepared statement
        pstmt.setString(1, firstname);
        pstmt.setString(2, lastname);
        pstmt.setString(3, gender);
        pstmt.setString(4, birthString); // Set SQL Date
        pstmt.setString(5, email);
        pstmt.setString(6, address);
        pstmt.setInt(7, classroom);
        pstmt.setTime(8, start);
        pstmt.setTime(9, end);
        pstmt.setInt(10, contact);
        System.out.println(birthString);
        // Execute the insert operation
        int rowsAffected = pstmt.executeUpdate();
        System.out.println(rowsAffected + " row(s) inserted.");

    } catch (SQLException ex) {
        Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, "SQL Error: ", ex);
    }
}



public void update () throws ParseException{
    
    int id =Integer.parseInt(idtxt.getText());
    String firstname=firstnametxt.getText();
    String lastname=lastnametxt.getText();
    String gender=gendertxt.getSelectedItem().toString();
    String email=emailtxt.getText();
    String address=addresstxt.getSelectedItem().toString();
    
    int classroom=Integer.parseInt(classtxt.getText());
    
    DateFormat timeFormatter = new SimpleDateFormat("HH:mm");

    // Convert start and end strings to java.sql.Time
    Time start = new Time(timeFormatter.parse(starttxt.getText()).getTime()); // Assuming you have a field named starttxt
    Time end = new Time(timeFormatter.parse(endtxt.getText()).getTime());
    
    int contact =Integer.parseInt(contacttxt.getText());
    String birth =birthdatetxt.getDate().toString();
    
    String updateQuery="CALL UpdateStudent(?,?,?,?,?,?,?,?,?,?,?)";
    
    try (Connection con = Connect.getConnection(); 
         PreparedStatement pstmt = con.prepareStatement(updateQuery))
         {
        
        // Set parameters for the prepared statement
        pstmt.setInt(1,id);
        pstmt.setString(2, firstname);
        pstmt.setString(3, lastname);
        pstmt.setString(4, gender);
        pstmt.setString(5,birth);
        pstmt.setString(6, email);
        pstmt.setString(7, address);
        
        pstmt.setInt(8, classroom);
        pstmt.setTime(9, start);
        pstmt.setTime(10,end);
        pstmt.setInt(11,contact);
        
        
        // Execute the insert operation
        int rowsAffected = pstmt.executeUpdate();
        Student_information.TB(jTable2);

}       catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
    Student_information.TB(jTable2);
}



public void Delete(){
        int delete=Integer.parseInt(idtxt.getText());
        String deleteQuery="""
                          CALL DeleteStudent(?);""";
        try (Connection con = Connect.getConnection(); 
         PreparedStatement pstmt = con.prepareStatement(deleteQuery))
         {
             pstmt.setInt(1,delete);
        System.out.println(delete);
        int rowsAffected = pstmt.executeUpdate();
    }   catch (SQLException ex) {
           
        }
        Student_information.TB(jTable2);
    }

//public void setclass(){
//    int level=Integer.parseInt(leveltxt.getSelectedItem().toString());
//    String classquery="SELECT DISTINCT roomNumber  FROM class WHERE Level=?; ";
//    try(Connection con =Connect.getConnection();
//        PreparedStatement pstmt=con.prepareStatement(classquery);
//        ){
//        pstmt.setInt(1, level);
//        classtxt.removeAllItems();
//        try(ResultSet rs=pstmt.executeQuery()){
//            while(rs.next()){
//            int classroom=rs.getInt("roomNumber");
//            String parseclass=Integer.toString(classroom);
//            classtxt.addItem(parseclass);
//        }
//        }
//        
//        
//    }   catch (SQLException ex) {
//            Logger.getLogger(CourseEdit.class.getName()).log(Level.SEVERE, null, ex);
//        }  

//}
//public void setstarttime() {
//    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
//
//    String timeQuery = """
//        SELECT starttime FROM class
//        WHERE roomnumber = ?;
//    """;
//
//    int classnumber = Integer.parseInt(classtxt.getSelectedItem().toString());
//
//    try (Connection con = Connect.getConnection();
//         PreparedStatement pstmt = con.prepareStatement(timeQuery)) {
//
//        pstmt.setInt(1, classnumber);
//
//        try (ResultSet rs = pstmt.executeQuery()) {
//            classtxt.removeAllItems(); // Clear starttxt JComboBox
//
//            while (rs.next()) {
//                Time startTime = rs.getTime("starttime");
//                
//                if (startTime != null) {
//                    LocalTime localStartTime = startTime.toLocalTime();
//                    String start = localStartTime.format(formatter);
//                    
//                    classtxt.addItem(start); // Add formatted time to starttxt JComboBox
//                }
//            }
//        }
//    } catch (SQLException ex) {
//        Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, "Error fetching start times", ex);
//    }
//}
//
//public void setendtime() {
//    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
//
//    String timeQuery = """
//        SELECT endtime FROM class
//        WHERE roomnumber = ? AND starttime = ?;
//    """;
//
//    int classnumber = Integer.parseInt(classtxt.getSelectedItem().toString());
//    String startText = classtxt.getSelectedItem().toString();
//
//    LocalTime start = LocalTime.parse(startText, formatter);
//
//    try (Connection con = Connect.getConnection();
//         PreparedStatement pstmt = con.prepareStatement(timeQuery)) {
//
//        pstmt.setInt(1, classnumber);
//        pstmt.setTime(2, Time.valueOf(start));
//
//        try (ResultSet rs = pstmt.executeQuery()) {
//            endtxt.removeAllItems(); // Clear endtxt JComboBox
//
//            while (rs.next()) {
//                Time endTime = rs.getTime("endtime");
//                
//                if (endTime != null) {
//                    LocalTime localEndTime = endTime.toLocalTime();
//                    String end = localEndTime.format(formatter);
//                    
//                    endtxt.addItem(end); // Add formatted time to endtxt JComboBox
//                }
//            }
//        }
//    } catch (SQLException ex) {
//        Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, "Error fetching end times", ex);
//    }
//}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Edit().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> addresstxt;
    private com.github.lgooddatepicker.components.DatePicker birthdatetxt;
    private javax.swing.JTextField classtxt;
    private javax.swing.JTextField contacttxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField endtxt;
    private javax.swing.JTextField firstnametxt;
    private javax.swing.JComboBox<String> gendertxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField lastnametxt;
    private javax.swing.JTextField starttxt;
    // End of variables declaration//GEN-END:variables
}
