/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_management_system;

import Crud.CourseEdit;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import student_management_system.Class.Connect;
import student_management_system.Class.Course_data;
import java.sql.Connection;
import java.sql.*;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author MSI
 */
public final class Course_management extends javax.swing.JFrame {

    /**
     * Creates new form Main_navigation
     */
    public Course_management() {

        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        student_information_btn = new javax.swing.JButton();
        Manage_course_btn = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        student_information_btn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlabel_head = new javax.swing.JLabel();
        big_container = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(900, 800));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 573));

        student_information_btn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        student_information_btn.setForeground(new java.awt.Color(153, 153, 255));
        student_information_btn.setText("Student Information");
        student_information_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_information_btnActionPerformed(evt);
            }
        });

        Manage_course_btn.setBackground(new java.awt.Color(153, 153, 255));
        Manage_course_btn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Manage_course_btn.setForeground(new java.awt.Color(255, 255, 255));
        Manage_course_btn.setText("Manage courses");
        Manage_course_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_course_btnActionPerformed(evt);
            }
        });

        home_btn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        home_btn.setForeground(new java.awt.Color(153, 153, 255));
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });

        student_information_btn1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        student_information_btn1.setForeground(new java.awt.Color(153, 153, 255));
        student_information_btn1.setText("Teacher");
        student_information_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_information_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(student_information_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Manage_course_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(home_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student_information_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(student_information_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(student_information_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(Manage_course_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1100, 911));

        jlabel_head.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlabel_head.setForeground(new java.awt.Color(153, 153, 255));
        jlabel_head.setText("Course management");

        big_container.setBackground(new java.awt.Color(255, 255, 255));

        container.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout big_containerLayout = new javax.swing.GroupLayout(big_container);
        big_container.setLayout(big_containerLayout);
        big_containerLayout.setHorizontalGroup(
            big_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, big_containerLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        big_containerLayout.setVerticalGroup(
            big_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(big_containerLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EDIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(big_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlabel_head)
                        .addGap(376, 376, 376))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlabel_head)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(big_container, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void student_information_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_information_btnActionPerformed
        Student_information nav_Student_information=new Student_information();
        nav_Student_information.show();
        dispose();
    }//GEN-LAST:event_student_information_btnActionPerformed

    private void Manage_course_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_course_btnActionPerformed
        Course_management nav_course_management=new Course_management();
        nav_course_management.show();
        dispose();
    }//GEN-LAST:event_Manage_course_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        Main_dashboard nav_main_dashboard=new Main_dashboard();
        nav_main_dashboard.show();
        dispose();
    }//GEN-LAST:event_home_btnActionPerformed

    private void student_information_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_information_btn1ActionPerformed
        Teacher nav_teacher=new Teacher();
        nav_teacher.show();
        dispose();
    }//GEN-LAST:event_student_information_btn1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CourseEdit courseEdit_nav=new CourseEdit();
        courseEdit_nav.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
public List<Course_data> datalist() {
    List<Course_data> teachers = new ArrayList<>();
    try (Connection con = Connect.getConnection(); Statement state = con.createStatement()) {
        String query = """
                SELECT * FROM class 
                LEFT JOIN teacher ON class.teacherID = teacher.idteacher
                INNER JOIN subject ON class.subjectid = subject.idsubject
                ORDER BY roomnumber;""";

        try (ResultSet rs = state.executeQuery(query)) {
            while (rs.next()) {
                int teacherID = rs.getInt("teacherid");
                int classID = rs.getInt("roomnumber");
                String subject = rs.getString("subject_name");
                int level=rs.getInt ("level");
                String fullName = rs.getString("fullname");
                String start = rs.getString("starttime");
                String end = rs.getString("endtime");

                // Create a new Course_data instance and add it to the list
                Course_data courseData = new Course_data(teacherID, classID, subject,level, fullName, start, end);
                teachers.add(courseData);
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(Course_management.class.getName()).log(Level.SEVERE, null, ex);
    }
    return teachers;
}

public void init() {
    List<Course_data> courseList = datalist();

    // Initialize container JPanel and set layout
//    JPanel container = new JPanel();
    container.setLayout(new GridLayout(0, 3, 50, 50)); // 3 columns, dynamic rows

    // Set fixed size for the container JPanel
//    container.setPreferredSize(new Dimension(900, 180)); // Fixed size for the container

    // Loop to create and add child JPanels
    for (Course_data course : courseList) {
        String start = course.getStart().substring(0, 5);
        String end = course.getEnd().substring(0, 5);

        JPanel childPanel = new JPanel();
        childPanel.setLayout(new GridLayout(5, 2)); // 4 rows, 2 columns, with gaps

        // Set fixed size for the child panel
        childPanel.setPreferredSize(new Dimension(0, 150)); // Fixed size for each child panel

        // Add JLabels to the child panel
        JLabel label1 = new JLabel("  Class :");
        JLabel classtxt = new JLabel(Integer.toString(course.getClassID()));
        JLabel label3 = new JLabel("  Teacher:");
        JLabel fullnametxt = new JLabel(course.getFullName());
        JLabel label2 = new JLabel("  Subject:");
        JLabel subjecttxt = new JLabel(course.getSubject());
        JLabel label4=new JLabel("  Level:");
        JLabel leveltxt=new JLabel(Integer.toString(course.getLevel()));
        JLabel label5 = new JLabel("  Time:");
        JLabel timetxt = new JLabel(start + " - " + end);

        JLabel[] arr = {label1, classtxt, label2, subjecttxt, label3, fullnametxt, label4,leveltxt,label5, timetxt};
        for (JLabel key2 : arr) {
            key2.setForeground(Color.white);
            key2.setFont(new Font("Times New Roman", Font.BOLD, 18));
        }

        // Add labels to the child panel
        childPanel.add(label1);
        childPanel.add(classtxt);
        childPanel.add(label3);
        childPanel.add(fullnametxt);
        childPanel.add(label2);
        childPanel.add(subjecttxt);
        childPanel.add(label4);
        childPanel.add(leveltxt);
        childPanel.add(label5);
        childPanel.add(timetxt);

        // Set background of child panel
        childPanel.setBackground(new Color(153, 153, 255));

        // Handle mouse click events
        childPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int classID = course.getClassID();
                String start=course.getStart();
                String end=course.getEnd();
                System.out.println("Class ID: " + classID);
                System.out.println("start:" + start);
                System.out.println("end:" + end);

                Course_management_info classinfo = new Course_management_info();
                try {
                    classinfo.settitle(classID, start, end);
                    dispose();
                } catch (SQLException | ParseException ex) {
                    Logger.getLogger(Course_management.class.getName()).log(Level.SEVERE, null, ex);
                }
                classinfo.show();
                // Uncomment if you want to close the current window
                // dispose();
            }
        });

        // Add the child panel to the container
        container.add(childPanel);
    }
//    JPanel newContainer=new JPanel();
//    newContainer.add(container);
//    newContainer.setBackground(Color.WHITE);
    

    // Wrap the container JPanel in a JScrollPane
    JScrollPane scrollPane = new JScrollPane(container);
    scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
//
//    // Set preferred size for JScrollPane (optional, if you want to control the JScrollPane size)
//    scrollPane.setPreferredSize(new Dimension(1200, 400));
//
//    // Add the JScrollPane to the big_container panel
    big_container.setLayout(new BorderLayout());
    big_container.add(scrollPane, BorderLayout.CENTER);
}



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course_management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course_management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton Manage_course_btn;
    private javax.swing.JPanel big_container;
    private javax.swing.JPanel container;
    javax.swing.JButton home_btn;
    private javax.swing.JButton jButton1;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JLabel jlabel_head;
    javax.swing.JButton student_information_btn;
    javax.swing.JButton student_information_btn1;
    // End of variables declaration//GEN-END:variables
}
